server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  application:
    name: ganyu-service
  messages:
    encoding: UTF-8
    basename: validation-messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 10000
      max-lifetime: 100000
      maximum-pool-size: 10
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: LOWER_CAMEL_CASE
  mail:
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 10000
          writetimeout: 5000
          auth: true
          starttls:
            enable: true
            required: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: '86400000'
      refresh-token-expiration: '604800000'
      read-header: Authorization

logging:
  pattern:
    level: "%5p ${spring.application.name:test} [%X{traceId:-}-%X{spanId:-}]"